name: Publish to NPM

on:
  push:
    branches:
      - main
    paths:
      - 'search-sdk/**'
      - 'env-suggestion-sdk/**'
  release:
    types: [published]

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      search-sdk-changed: ${{ steps.changes.outputs.search-sdk }}
      env-suggestion-sdk-changed: ${{ steps.changes.outputs.env-suggestion-sdk }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      
      - name: Check for changes
        id: changes
        run: |
          if git diff --name-only HEAD~1 HEAD | grep -q "^search-sdk/"; then
            echo "search-sdk=true" >> $GITHUB_OUTPUT
          else
            echo "search-sdk=false" >> $GITHUB_OUTPUT
          fi
          
          if git diff --name-only HEAD~1 HEAD | grep -q "^env-suggestion-sdk/"; then
            echo "env-suggestion-sdk=true" >> $GITHUB_OUTPUT
          else
            echo "env-suggestion-sdk=false" >> $GITHUB_OUTPUT
          fi

  publish-search-sdk:
    needs: detect-changes
    if: needs.detect-changes.outputs.search-sdk-changed == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
          
      - name: Install dependencies
        run: |
          cd search-sdk
          npm install
          
      - name: Build package
        run: |
          cd search-sdk
          npm run build
          
      - name: Check if version changed
        id: version-check
        run: |
          cd search-sdk
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          PUBLISHED_VERSION=$(npm view @docstar-packages/search-sdk version 2>/dev/null || echo "0.0.0")
          echo "package-version=$PACKAGE_VERSION" >> $GITHUB_OUTPUT
          echo "published-version=$PUBLISHED_VERSION" >> $GITHUB_OUTPUT
          if [ "$PACKAGE_VERSION" != "$PUBLISHED_VERSION" ]; then
            echo "should-publish=true" >> $GITHUB_OUTPUT
          else
            echo "should-publish=false" >> $GITHUB_OUTPUT
          fi
          
      - name: Publish to NPM
        if: steps.version-check.outputs.should-publish == 'true'
        run: |
          cd search-sdk
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          
      - name: Create GitHub Release
        if: steps.version-check.outputs.should-publish == 'true'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: search-sdk-v${{ steps.version-check.outputs.package-version }}
          name: Search SDK v${{ steps.version-check.outputs.package-version }}
          body: |
            Changes in this Release:
            - Updated search-sdk to version ${{ steps.version-check.outputs.package-version }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-env-suggestion-sdk:
    needs: detect-changes
    if: needs.detect-changes.outputs.env-suggestion-sdk-changed == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
          
      - name: Install dependencies
        run: |
          cd env-suggestion-sdk
          npm install
          
      - name: Build package
        run: |
          cd env-suggestion-sdk
          npm run build
          
      - name: Check if version changed
        id: version-check
        run: |
          cd env-suggestion-sdk
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          PUBLISHED_VERSION=$(npm view @docstar-packages/env-suggestion-sdk version 2>/dev/null || echo "0.0.0")
          echo "package-version=$PACKAGE_VERSION" >> $GITHUB_OUTPUT
          echo "published-version=$PUBLISHED_VERSION" >> $GITHUB_OUTPUT
          if [ "$PACKAGE_VERSION" != "$PUBLISHED_VERSION" ]; then
            echo "should-publish=true" >> $GITHUB_OUTPUT
          else
            echo "should-publish=false" >> $GITHUB_OUTPUT
          fi
          
      - name: Publish to NPM
        if: steps.version-check.outputs.should-publish == 'true'
        run: |
          cd env-suggestion-sdk
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          
      - name: Create GitHub Release
        if: steps.version-check.outputs.should-publish == 'true'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: env-suggestion-sdk-v${{ steps.version-check.outputs.package-version }}
          name: Env Suggestion SDK v${{ steps.version-check.outputs.package-version }}
          body: |
            Changes in this Release:
            - Updated env-suggestion-sdk to version ${{ steps.version-check.outputs.package-version }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
