name: Publish JavaScript Script

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  release:
    types: [published]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pages: write
      id-token: write
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Build Search SDK
      run: |
        cd search-sdk
        node build.js
        
    - name: Copy example page
      run: |
        cp example.html search-sdk/
        
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./search-sdk
        publish_branch: gh-pages
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: search-sdk-dist
        path: search-sdk/dist/

  release:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Build Search SDK
      run: |
        cd search-sdk
        node build.js
        
    - name: Create release archive
      run: |
        cd search-sdk
        zip -r ../docstar-search-sdk-${{ github.event.release.tag_name }}.zip dist/ README.md package.json
        
    - name: Upload release assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./docstar-search-sdk-${{ github.event.release.tag_name }}.zip
        asset_name: docstar-search-sdk-${{ github.event.release.tag_name }}.zip
        asset_content_type: application/zip
