name: Publish JavaScript Script

on:
  push:
    branches: [ main, master ]
    paths:
      - 'search-sdk/**'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'search-sdk/**'
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Build Search SDK
      run: |
        cd search-sdk
        node build.js
        
    - name: Create example page
      run: |
        cd search-sdk
        cat > example.html << 'EOF'
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>DocStar Search SDK - Live Demo</title>
            <style>
                body {
                    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
                    max-width: 800px;
                    margin: 0 auto;
                    padding: 20px;
                    background-color: #f5f5f5;
                }
                .demo-section {
                    background: white;
                    padding: 30px;
                    border-radius: 12px;
                    margin-bottom: 30px;
                    box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
                }
                h1 { color: #333; text-align: center; margin-bottom: 10px; }
                .subtitle { text-align: center; color: #666; margin-bottom: 40px; }
                .search-container { margin: 20px 0; }
                .instructions {
                    background: #e3f2fd;
                    border: 1px solid #2196f3;
                    border-radius: 6px;
                    padding: 15px;
                    margin: 15px 0;
                    color: #1565c0;
                }
                .code-example {
                    background: #f8f9fa;
                    border: 1px solid #e9ecef;
                    border-radius: 6px;
                    padding: 15px;
                    margin: 15px 0;
                    font-family: 'Monaco', 'Menlo', 'Ubuntu Mono', monospace;
                    font-size: 14px;
                    overflow-x: auto;
                }
                .cdn-links {
                    background: #f0f8ff;
                    border: 1px solid #0066cc;
                    border-radius: 6px;
                    padding: 20px;
                    margin: 20px 0;
                }
                .cdn-links h3 { margin-top: 0; color: #0066cc; }
                .cdn-link {
                    background: #fff;
                    border: 1px solid #ddd;
                    border-radius: 4px;
                    padding: 8px 12px;
                    margin: 8px 0;
                    font-family: monospace;
                    font-size: 14px;
                    word-break: break-all;
                }
            </style>
        </head>
        <body>
            <h1>DocStar Search SDK</h1>
            <p class="subtitle">Simple search input with console logging</p>

            <div class="cdn-links">
                <h3>🚀 Use via CDN</h3>
                <p><strong>Minified (Production):</strong></p>
                <div class="cdn-link">https://cdn.jsdelivr.net/gh/swayammaheshwari/docstar-sdk@latest/search-sdk/dist/docstar-search.min.js</div>
                
                <p><strong>Development:</strong></p>
                <div class="cdn-link">https://cdn.jsdelivr.net/gh/swayammaheshwari/docstar-sdk@latest/search-sdk/dist/docstar-search.js</div>
            </div>

            <div class="demo-section">
                <h2>Live Demo</h2>
                <div class="instructions">
                    💡 Type something and press Enter. Check the browser console (F12) to see the logged output.
                </div>
                
                <div id="demo-search" class="search-container"></div>
                
                <div class="code-example">
        &lt;script src="https://cdn.jsdelivr.net/gh/swayammaheshwari/docstar-sdk@latest/search-sdk/dist/docstar-search.min.js"&gt;&lt;/script&gt;
        &lt;div id="my-search"&gt;&lt;/div&gt;
        &lt;script&gt;
            SimpleSearch.create({
                containerId: 'my-search',
                placeholder: 'Search...'
            });
        &lt;/script&gt;
                </div>
            </div>

            <div class="demo-section">
                <h2>Auto-initialization</h2>
                <div class="instructions">
                    💡 Using data attributes for automatic initialization.
                </div>
                
                <div 
                    id="auto-search" 
                    data-simple-search
                    data-placeholder="Auto-initialized search..."
                    class="search-container">
                </div>
                
                <div class="code-example">
        &lt;div 
            id="auto-search" 
            data-simple-search
            data-placeholder="Auto-initialized search..."&gt;
        &lt;/div&gt;
                </div>
            </div>

            <script src="dist/docstar-search.min.js"></script>
            <script>
                // Demo search
                SimpleSearch.create({
                    containerId: 'demo-search',
                    placeholder: 'Type here and press Enter...'
                });

                console.log('DocStar Search SDK loaded! Version:', SimpleSearch.version);
                console.log('Try typing in the search boxes above and pressing Enter.');
            </script>
        </body>
        </html>
        EOF
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: search-sdk-dist
        path: search-sdk/dist/
        
    - name: Upload example page
      uses: actions/upload-artifact@v4
      with:
        name: search-sdk-example
        path: search-sdk/example.html


  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: search-sdk-dist
        path: search-sdk/dist/
        
    - name: Create release archive
      run: |
        cd search-sdk
        zip -r ../docstar-search-sdk-${{ github.event.release.tag_name }}.zip dist/ README.md package.json
        
    - name: Upload release assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./docstar-search-sdk-${{ github.event.release.tag_name }}.zip
        asset_name: docstar-search-sdk-${{ github.event.release.tag_name }}.zip
        asset_content_type: application/zip
